
all: appli

appli: command.cpp container.cpp filesystem.cpp hexa.cpp main.cpp options.cpp stringeval.cpp
	g++ -std=c++11 command.cpp container.cpp filesystem.cpp hexa.cpp main.cpp options.cpp stringeval.cpp -o appli.exe